[package]
name = "kvs"
version = "0.1.0"
authors = ["Spencer Leslie <spencerdleslie@gmail.com>"]
description = "A key value store - from pcap tutorials"
edition = "2018"

[dependencies]
structopt = "0.2"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"